### PR TITLE
fix(typescript): remove resolver shortcut that splits module resolution caches

### LINKED ISSUE #5995: vue-tsc 3.0.2: ComponentCustomProperties augmentations dropped from component instance type
### Environment

- vue-tsc: 3.0.2 (works on 3.0.1)
- @vue/language-core: 3.0.2 (works on 3.0.1)
- TypeScript: 5.9.3
- Vue: 3.5.28
- Nuxt: 4.3.1 (but not Nuxt-specific)
- OS: macOS

### Describe the bug

After upgrading from `vue-tsc@3.0.1` to `3.0.2`, `ComponentCustomProperties` augmentations from `declare module 'vue'` blocks are no longer merged into the component instance type in `.vue` file templates.

This causes `$route`, `$router` (from vue-router's augmentation), and all auto-imported utilities (from Nuxt's generated `imports.d.ts` augmentation) to be missing from the component instance type. The `$nuxt` property (from a separate `plugins.d.ts` augmentation using `extends`) IS present, suggesting the issue is specific to how certain `ComponentCustomProperties` augmentations are merged.

Example error:
```
app/app.vue(5,24): error TS2339: Property '$route' does not exist on type
'{ member: ...; ... 18 more ...; $nuxt: NuxtApp; }'.
```

The type includes `$nuxt: NuxtApp` (from `plugins.d.ts`) but drops all properties from:
- vue-router's `ComponentCustomProperties` augmentation (`$route`, `$router`)
- Nuxt's `imports.d.ts` `ComponentCustomProperties` augmentation (~430 auto-imported utilities)

### Reproduction

I have not been able to create a minimal standalone reproduction — the issue only manifests in a larger project (~110 `.vue` files, multiple Nuxt modules). A fresh Nuxt project with the same modules and even the same `.vue` files copied over does not reproduce it. This suggests the issue may be related to module resolution order, the number of type declarations being merged, or interaction with `unplugin-vue-router` installing a second copy of `@vue/language-core` (3.2.x alongside the 3.0.x from vue-tsc).

### Bisection

- `vue-tsc@3.0.1` (`@vue/language-core@3.0.1`, `@volar/language-core@2.4.17`): **WORKS**
- `vue-tsc@3.0.2` (`@vue/language-core@3.0.2`, `@volar/language-core@2.4.19`): **BROKEN**
- All subsequent versions (3.1.0, 3.2.x) are also broken.

### What works vs. what doesn't

| Augmentation source | Mechanism | Works? |
|---|---|---|
| `plugins.d.ts` | `interface ComponentCustomProperties extends NuxtAppInjections {}` | Yes |
| `imports.d.ts` | `interface ComponentCustomProperties { readonly navigateTo: ...; ... }` | No |
| vue-router types | `interface ComponentCustomProperties { $route: ...; $router: ...; }` | No |

### Additional context

- The generated `.d.ts` files are valid and correctly structured
- The augmentations use standard `declare module 'vue' { interface ComponentCustomProperties { ... } }` syntax
- Pinning `vue-tsc` to `3.0.1` resolves all errors
- The project has two copies of `@vue/language-core` in node_modules: one from `vue-tsc` (3.0.x) and one from `unplugin-vue-router` (3.2.x) — this dual version may be a contributing factor

### PR DESCRIPTION
**Pull request by zlotnika**
The resolveModuleNameLiterals and resolveModuleNames hooks have a shortcut: files whose imports don't end with a plugin extension (.vue) bypass the custom resolver and use the original host's resolver. This means files that augment `'vue'` (Nuxt's `imports.d.ts`, `plugins.d.ts`) go through a different resolution cache than files that import `.vue` components (`components.d.ts`). TypeScript treats the `'vue'` module resolved through each cache as separate module identities, so `ComponentCustomProperties` augmentations (`$route`, `navigateTo`, etc.) are dropped from the component instance type in templates.

This PR removes both shortcuts so all files use the custom resolver with a single shared `moduleResolutionCache`. The shortcut was a performance optimization, but in testing it actually shows no regression — the reproduction case is faster without it (1s vs 3.4s), likely because the single cache avoids redundant resolution work.

Tested against the reproduction at https://github.com/zlotnika/nuxt-34562-repro and a production Nuxt 4 project with vue 3.5.32, nuxt 4.4.2, 110+ components, and 7 modules.

Fixes vuejs/language-tools#5995

### CODE REVIEW

**Comment by zlotnika** [comment]
Closing this — after deeper investigation, the root cause is duplicate `vue` copies in `node_modules`, not the resolver shortcut.

When bun installs a nested `vue` inside `nuxt/node_modules/vue` (because the root-pinned version differs from nuxt's resolved version), TypeScript sees two separate `'vue'` module identities. Augmentations declared against one copy don't apply to components resolved through the other.

Deduplicating vue (removing `nuxt/node_modules/vue` so both use the root copy) fixes the issue across all tested versions, with no changes to volar needed.

I'll update vuejs/language-tools#5995 with this finding.
