### ISSUE TITLE
Has the buildMappings function been removed?

### ISSUE THREAD

**Issue by taku-y-9308** [volarjs/volar.js#209]
I get the following error when I run vue-tsc
```
TypeError: (0 , language_core_1.buildMappings) is not a function
```

I think I get this error when I upgrade @volar/language-core to 2.3.1.
Downgrading @volar/language-core to 2.3.0 did not cause the error.

**Comment by johnsoncodehk** [comment]
Sorry for the confusion, yes this function has been moved to `@vue/language-core`. You can copy the following code into your project if you need.

https://github.com/johnsoncodehk/language-tools-1/commit/dc526cc0697aa09b41e44ac119f25e33a3aca621#diff-b44337e00ad731e17c4611d4583c3a3a7e48fecd70ff7a2d51cdda5e60a6db39
